language: php
php:
  - 7.1
  - 7.2
  - 7.3

install:
  - travis_retry composer install --no-progress --no-interaction --prefer-dist

script:
  - vendor/bin/tester -s -p php -c ./tests/php.ini-unix tests

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

jobs:
  include:
    - env: title="Lowest Dependencies 7.1"
      php: 7.1
      install:
        - travis_retry composer update --no-progress --no-interaction --prefer-dist --prefer-lowest
      script:
        - vendor/bin/tester -s -p php -c ./tests/php.ini-unix tests
